[package]
name = "lb-server"
version = "0.1.0"
edition.workspace = true

[dependencies]
lb-core = { path = "../lb-core" }
lb-ratelimit = { path = "../lb-ratelimit" }
lb-balancer = { path = "../lb-balancer" }
lb-healthcheck = { path = "../lb-healthcheck" }
lb-proxy = { path = "../lb-proxy" }
lb-tcp = { path = "../lb-tcp" }
hyper = { version = "1", features = ["server", "http1"] }
hyper-util = { version = "0.1", features = ["tokio"] }
tokio = { version = "1", features = [
    "rt-multi-thread",
    "macros",
    "net",
    "signal",
    "time",
    "io-util",
    "sync",
] }
reqwest = "0.12"

[dev-dependencies]
reqwest = "0.12"
bytes = "1"
http-body-util = "0.1"
