[package]
name = "lb-ratelimit"
version.workspace = true
edition.workspace = true

[dependencies]
lb-core = { path = "../lb-core" }
dashmap = "6"
tokio = { version = "1", features = ["rt", "time", "macros", "sync"] }

[dev-dependencies]
lb-core = { path = "../lb-core", features = ["test-util"] }
tokio = { version = "1", features = ["rt", "macros", "time", "test-util"] }
